[[example-cache]]
= Custom Cache-Control headers

The `cacheControl` link:#example-options[option] controls the link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control['Cache-Control'] string that's returned in the header with a successful resource fetch. The string value, if any, directs the intraction between a browser and the server on subsequent requests for the same resource. By link:#behaviour[default] the string `"public, max-age=31536000, immutable"` is returned, the `cacheControl` option overrides this to return a different string, or switch it off:

Setting it to the **boolean** `false` means turning the entire cache-control header off in the response:
[source,javascript,options="nowrap"]
----
const getStatic = libStatic.buildGetter({
    root: 'my/folder',
    cacheControl: false
});
----

Setting it as a **string** instead, always returns that string:
[source,javascript,options="nowrap"]
----
const getStatic = libStatic.buildGetter({
    root: 'my/folder',
    cacheControl: 'immutable'
});
----

It can also be set as a **function**: `(path, resource, mimeType) => cacheControlString?`, for fine-grained control. For particular circumstances, return a cache-control string for override, or `false` for leaving it out, or `null` to fall back to the default cache-control string `"public, max-age=31536000, immutable"`:

[source,javascript,options="nowrap"]
----
const getStatic = libStatic.buildGetter({
    root: 'my/folder',
    cacheControl: function(path, resource, mimeType) {
        if (path.startsWith('/uncached')) {
            return false;
        }
        if (mimeType==='text/plain') {
            return "max-age=3600";
        }
        if (resource.getSize() < 100) {
            return "no-cache";
        }
        return null;
    }
});
----

👉 See the link:#options[options API reference] below, and link:#mutable-assets[handling mutable and immutable assets], for more details.
