[[example-content]]
= Custom content type handling

By default, lib-static detects link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types[MIME-type] automatically. But you can use the `contentType` link:options#example-options[option] to override it. Either way, the result is a string returned with link:../api/#behaviour[the response object].

If set as the **boolean** `false`, the detection and handling is switched off and no `Content-Type` header is returned:
[source,javascript,options="nowrap"]
----
const getStatic = libStatic.buildGetter({
    root: 'my/folder',
    contentType: false // <-- Empty string does the same
});
----

If set as a (non-empty) **string**, there will be no processing, but that string will be returned as a fixed content type (a bad idea for handling multiple resource types, of course):
[source,javascript,options="nowrap"]
----
const getStatic = libStatic.buildGetter({
    root: 'my/folder',
    contentType: "everything/thismimetype"
});
----

If set as an **object**, keys are file types (that is, the extensions of the requested asset file names, so beware of file extensions changing during compilation. To be clear, you want the post-compilation extension) and values are the returned MIME-type strings:
[source,javascript,options="nowrap"]
----
const getStatic = libStatic.buildGetter({
    root: 'my/folder',
    contentType: {
        json: "application/json",
        mp3: "audio/mpeg",
        TTF: "font/ttf"
    }
});
----
For any extension not found in that object, it will fall back to automatically detecting the type, so you can override only the ones you're interested in and leave the rest.

It can also be set as a **function**: `(path, resource) => mimeTypeString?` for fine-grained control: for each circumstance, return a specific mime-type string value, or `false` to leave the `contentType` out of the response, or `null` to fall back to lib-static's built-in detection:
[source,javascript,options="nowrap"]
----
const getStatic = libStatic.buildGetter({
    root: 'my/folder',
    contentType: function(path, resource) {
        if (path.endsWith('.myspoon') && resource.getSize() > 10000000) {
            return "media/toobig";
        }
        return null;
    }
});
----

👉 link:../api/index#options[Options API reference]
