[[example-get]]
= Low-level: .get

Lib-static exposes a second function `.get` (in addition to `.buildGetter`), for doing a direct resource fetch when the resource path is already known/resolved. The idea is to allow closer control with each call: implement your own logic and handling around it.

NOTE: For most scenarios though, you'll probably want to use link:../api/buildGetter#api-buildgetter[`.buildGetter`].

==== a) Similarities
- Just like the getter function returned by `.buildGetter`, `.get` also returns a link:../api/index#behaviour[full response object] with status, body, content type and a generated ETag, and has error detection and corresponding responses (statuses 400, 404 and 500).
- The link:../api/index#options[options] are also mostly the same.

==== b) Differences
`.get` is different from `.buildGetter` in these ways:

- `.get` is intended for lower-level usage (wraps less functionality, but gives the opportunity for even more controlled usage).
- Only one call: whereas `.buildGetter` sets up a reusable getter function, `.get` _is_ the getter function.
- No root folder is set up with `.get`. In every call, instead of the `request` argument, `.get` takes a full, absolute resource `path` (relative to JAR root) string. This allows _any valid path_ inside the JAR except the root `/` itself - including source code! **Be careful** how you resolve the `path` string in the controller to avoid security flaws, such as opening a service to reading _any file in the JAR_, etc.
- Since `.get` doesn't resolve the resource path from the request, there's no `getCleanPath` override option here.
- There is no check in `.get` for matching ETag (`If-None-Match` header), and no functionality to return a body-less status 304. `.get` always tries to fetch the resource.
- There is no link:../api/index#index-fallback[index fallback] functionality in `.get`.


==== c) Examples

An example service _getSingleStatic.es6_ that always returns a particular asset _/public/my-folder/another-asset.css_ from the JAR:

.src/main/resources/services/getSingleStatic/getSingleStatic.es6
[source,javascript,options="nowrap"]
----

const libStatic = require('lib/enonic/static');

exports.get = (request) => {
    return libStatic.get('public/my-folder/another-asset.css');
};
----

This is equivalent with using the `path` attribute:

[source,javascript,options="nowrap"]
----
    // ...

    return libStatic.get({
        path: 'public/my-folder/another-asset.css'
    });

    // ...
----

It's also open to the same link:../api/index#options[options] as `.buildGetter` - except for `getCleanPath` which doesn't exist for `.get`:

[source,javascript,options="nowrap"]
----
    // ...

    return libStatic.get('public/my-folder/another-asset.css',
        {
            // ... options ...
        }
    );

    // OR if you prefer:

    return libStatic.get(
        {
            path: 'public/my-folder/another-asset.css',
            // ... more options ...
        }
    );

    // ...
----

👉 link:../api/get#api-get[.get API reference]
