[[example-path]]
= Path resolution and other endpoints

Usually, the path to the resource file (relative to the root folder) is link:service#example-service-urls[determined from the request]. Out of the box, this depends on a few things:

- The controller must be able to accept requests from sub-URI. For example, the controller handling requests to a root URI `/my/endpoint/` must also respond to `/my/endpoint/subpath`, `/my/endpoint/other/path`, etc.
- The incoming `request` in the controller object must contain a `rawPath` and `contextPath` attribute to compare, and the contextPath value must be the prefix in the rawPath value. For example, from this request...
+
[source,javascript,options="nowrap"]
----
{
  rawPath:     "/_/service/my.xp.app/servemyfolder/some/subdir/some.file",
  contextPath: "/_/service/my.xp.app/servemyfolder"
}
----
...the relative resource path is resolved to `"/some/subdir/some.file"`. And to recap: lib-static will look for `<root>/some/subdir/some.file`, where `root` is the folder that was set in `libStatic.buildGetter`.

{zwsp} +

All the previous examples use lib-static in link:https://developer.enonic.com/docs/xp/stable/runtime/engines/http-service[XP services], because services act exactly like this. The premises are fulfilled out of the box here, so the path resolution works without further setup.

However, lib-static can be used in other contexts than in services, where these premises may not be true and you may need to roll your own path resolution:

{zwsp} +

[[example-getcleanpath]]
== a) Override: getCleanPath

You can *override the default file path resolution* by implementing a `request => string` function, and add that as a `getCleanPath` option in `.buildGetter`.

👉 link:../api/index#options[Options API reference]

For example, a simplified version of the default could be implemented like this:

[source,javascript,options="nowrap"]
----
exports.get = libStatic.buildGetter({
    root: 'my/folder',
    getCleanPath: request => {
        const prefix = request.contextPath;
        return request.rawPath.substring(prefix.length);
    }
});
----

{zwsp} +

[[example-gotchas]]
== b) Gotchas

When writing a good `getCleanPath` function, here are some *rules of thumb*:

1. `request => string` function, where the string is the final resolved relative path under `<root>`
2. In order for index fallbacks to work properly:
  - URIs with a trailing slash should also return the trailing slash in the string,
  - And vice versa: URIs without a trailing slash should not return one,
  - URIs to the endpoint itself should return an empty string (unless there's a trailing slash, in which case only a slash should be returned),
  - For consistency, URIs to other content below the endpoint should return a path beginning with a slash.
3. Use `request.rawPath` as the basis. Don't use `request.path`.
  - The `.path` attribute has a less reliable behavior for lib-static's purpose: vhosting is kept, url entities may be escaped (which may evade some built-in security checks or fail to find files/folders with special characters in their names), and trailing slashes are stripped away (which makes index fallbacks impossible). The `.rawPath` attribute deals with these issues.
+
NOTE: XP version *7.7.1* is the first version where these issues are handled well. On earlier versions, trailing slashes are stripped from `.rawPath` too, so index fallback can't be expected to work. Upgrade XP if necessary.

The next examples show how to achieve this in contexts outside of services:
