const enum CACHE_CONTROL_DIRECTIVE {
  IMMUTABLE = 'immutable',
  MAX_AGE = 'max-age',
  MAX_STALE = 'max-stale',
  MIN_FRESH = 'min-fresh',
  MUST_REVALIDATE = 'must-revalidate',
  MUST_UNDERSTAND = 'must-understand',
  NO_CACHE = 'no-cache',
  NO_STORE = 'no-store',
  NO_TRANSFORM = 'no-transform',
  ONLY_IF_CACHED = 'only-if-cached',
  PRIVATE = 'private',
  PROXY_REVALIDATE = 'proxy-revalidate',
  PUBLIC = 'public',
  S_MAX_AGE = 's-maxage',
  STALE_IF_ERROR = 'stale-if-error',
  STALE_WHILE_REVALIDATE = 'stale-while-revalidate',
}

export const enum REQUEST_CACHE_CONTROL_DIRECTIVE {
  MAX_AGE = CACHE_CONTROL_DIRECTIVE.MAX_AGE,
  MAX_STALE = CACHE_CONTROL_DIRECTIVE.MAX_STALE,
  MIN_FRESH = CACHE_CONTROL_DIRECTIVE.MIN_FRESH,
  NO_CACHE = CACHE_CONTROL_DIRECTIVE.NO_CACHE,
  NO_STORE = CACHE_CONTROL_DIRECTIVE.NO_STORE,
  NO_TRANSFORM = CACHE_CONTROL_DIRECTIVE.NO_TRANSFORM,
  ONLY_IF_CACHED = CACHE_CONTROL_DIRECTIVE.ONLY_IF_CACHED,
  STALE_IF_ERROR = CACHE_CONTROL_DIRECTIVE.STALE_IF_ERROR
}

export const enum RESPONSE_CACHE_CONTROL_DIRECTIVE {
  IMMUTABLE = CACHE_CONTROL_DIRECTIVE.IMMUTABLE,
  MAX_AGE = CACHE_CONTROL_DIRECTIVE.MAX_AGE,
  MUST_REVALIDATE = CACHE_CONTROL_DIRECTIVE.MUST_REVALIDATE,
  MUST_UNDERSTAND = CACHE_CONTROL_DIRECTIVE.MUST_UNDERSTAND,
  NO_CACHE = CACHE_CONTROL_DIRECTIVE.NO_CACHE,
  NO_STORE = CACHE_CONTROL_DIRECTIVE.NO_STORE,
  NO_TRANSFORM = CACHE_CONTROL_DIRECTIVE.NO_TRANSFORM,
  PRIVATE = CACHE_CONTROL_DIRECTIVE.PRIVATE,
  PROXY_REVALIDATE = CACHE_CONTROL_DIRECTIVE.PROXY_REVALIDATE,
  PUBLIC = CACHE_CONTROL_DIRECTIVE.PUBLIC,
  S_MAX_AGE = CACHE_CONTROL_DIRECTIVE.S_MAX_AGE,
  STALE_IF_ERROR = CACHE_CONTROL_DIRECTIVE.STALE_IF_ERROR,
  STALE_WHILE_REVALIDATE = CACHE_CONTROL_DIRECTIVE.STALE_WHILE_REVALIDATE
}

export const enum HTTP2_REQUEST_HEADER {
  CACHE_CONTROL = 'cache-control',
  IF_NONE_MATCH = 'if-none-match'
}

export const enum HTTP2_RESPONSE_HEADER {
  CACHE_CONTROL = 'cache-control',
  ETAG = 'etag',
}

const DEFAULT_MAX_AGE = 31536000;

export const DEFAULT_CACHE_CONTROL = `${
  RESPONSE_CACHE_CONTROL_DIRECTIVE.PUBLIC}, ${
  RESPONSE_CACHE_CONTROL_DIRECTIVE.MAX_AGE}=${DEFAULT_MAX_AGE}, ${
  RESPONSE_CACHE_CONTROL_DIRECTIVE.IMMUTABLE}`;

export const DEFAULT_CACHE_CONTROL_WHEN_ETAG = `${RESPONSE_CACHE_CONTROL_DIRECTIVE.MAX_AGE}=3600`;

// export const HTTP2_REQUEST_HEADER_IF_NONE_MATCH = 'if-none-match';

// export const HTTP2_RESPONSE_HEADER_NAME_CACHE_CONTROL = 'cache-control';
// export const HTTP2_RESPONSE_HEADER_NAME_ETAG = 'etag';

export const CACHE_CONTROL_IMMUTABLE = `public, max-age=${DEFAULT_MAX_AGE}, immutable`;

export const CACHE_CONTROL_DEFAULT = `${
  RESPONSE_CACHE_CONTROL_DIRECTIVE.PUBLIC}, ${
  RESPONSE_CACHE_CONTROL_DIRECTIVE.MAX_AGE}=10, ${
  RESPONSE_CACHE_CONTROL_DIRECTIVE.STALE_WHILE_REVALIDATE}=50`;

export const INDEXFALLBACK_CACHE_CONTROL = RESPONSE_CACHE_CONTROL_DIRECTIVE.NO_CACHE

export const GETTER_ROOT = 'static';

export const RESPONSE_NOT_MODIFIED = {
    status: 304
} as const;

export const REGEX_PATH_DOUBLE_DOT = /\.\./;
export const REGEX_PATH_ILLEGAL_CHARS = /[<>:"'`´\\|?*]/;

