[[api-buildgetter]]
= .buildGetter

Sets up and returns a reusable resource-getter function.

Can be used in three ways:

`const getStatic = libStatic.buildGetter(root);`

`const getStatic = libStatic.buildGetter(root, options);`

`const getStatic = libStatic.buildGetter(optionsWithRoot);`

The getter function (`getStatic`) takes the link:https://developer.enonic.com/docs/xp/stable/framework/http#http-request[XP request object] as argument. `request` is used to determine the asset path, and to check the `If-None-Match` header. It then returns a link:#behaviour[response object] for the asset:

`const response = getStatic(request);`

An ETag value is generated and cached for the requested asset. If that matches the `If-None-Match` header in the request, the response will only contain: `{status: 304}`, signifying the asset hasn't changed and the cache can be used instead of downloading the asset. If there's no match, the asset will be read out and returned in the link:#behaviour[response] under `body`, with a `status` 200.


[[buildgetter-params]]
== Params:
- `root` (string): path to a root folder where resources are found. This string points to a root folder in the built JAR.
    > NOTE: The phrase _"a root folder in the built JAR"_ is accurate, but if you think JAR's can be a bit obscure here's an easier mental model: `root` points to a folder below and relative to the _build/resources/main_. This is where all assets are collected when building the JAR. And when running XP in link:https://developer.enonic.com/docs/enonic-cli/master/dev#start[dev mode], it actually IS where assets are served from. Depending on specific build setups, you can also think of `root` as being relative to _src/main/resources/_.
- `options` (object): add an link:#options[options object] after `path` to control behaviour for all responses from the returned getter function.
- `optionsWithRoot` (object): same as above: an link:#options[options object]. But when used as the first and only argument, this object _must_ also include a `{ root: ..., }` attribute too - a root string same as above. This is simply for convenience if you prefer named parameters instead of a positional `root` argument. If both are supplied, the positional `root` argument is used.

If `root` (either as a string argument or as an attribute in a `options` object) resolves to (or outside) the JAR root, contains `..` or any of the characters `: | < > ' " ´ * ?` or backslash or backtick, or is missing or empty, an error is thrown.

Again, you need to call the returned getter function to actually get a response.

👉 link:#example-service[Usage examples]
