[[api]]
== API: functions

Three controller functions are exposed.

- The first, link:buildgetter#api-buildgetter[buildgetter], is a broad configure-once/catch-all approach that's based on the relative path in the request. This is the one you usually want.
- The second, link:get#api-get[get], specifically gets an asset based on a path string and options for each particular call.
- The third, link:getstaticurl[getStaticUrl], is a helper function that generates a URL pointing to a static file.

👉 link:get#example-get[Similarities and differences]

* <<buildgetter#, buildGetter>>
* <<get#, get>>
* <<getStaticUrl#, getStaticUrl>>

[[behaviour]]
== API: response and default behaviour
Unless some of these aspects are overriden by an link:../api/index#options[options parameter], the returned object (from both `.get` and the getter function created by `.buildGetter`) is a standard link:https://developer.enonic.com/docs/xp/stable/framework/http#http-response[XP response object] ready to be returned from an XP controller.

**Response signature:**

----
{ status, body, contentType, headers }
----

For example:

----
{
    status: 200,
    body: "I am some content",
    contentType: "text/plain",
    headers: {
        'Cache-Control': 'public, max-age=31536000, immutable',
        ETag: '"12a39b87c43d7e4f5"'
    }
}
----

👉  link:#example-output[Output: intro/example]

{zwsp} +

[[index-fallback]]
==== Index fallback

If the URL points to a folder instead of a file, and that folder contains a fallback file (`index.html`), the fallback file is served with the appropriate contentType and a cache-busting Cache-Control header.

If the folder-name URL does not end with a trailing slash, this slash is automatically added via a redirect. This is to ensure that later relative links will work.

This is a feature in link:#api-buildgetter[.buildGetter], but not link:#api-get[.get] - if you use .get you must implement it yourself.

[[osgi-bug]]
NOTE: A workaround for a link:https://issues.apache.org/jira/browse/FELIX-6294[a bug in the underlying OSGi system] causes the following behaviour in current versions of lib-static: directories can be referenced to get an index fallback both with and without a trailing slash - but **empty files cannot be served and will cause a status `404` response instead**. When a fix for the underlying bug is available, lib-static will be updated to support both empty files and directories with index fallback.



{zwsp} +

[[status]]
==== status

Standard link:https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[HTTP error codes]:

- `200` (OK): successful, resource fetched. Either the resource path pointed to a readable file, or to a folder where a link:#index-fallback[index fallback] file was found (index fallback is an automatic feature of link:#api-buildgetter[.buildGetter], but not link:#api-get[.get]).
- `303` (Redirect): resource path hit a folder with an index fallback file in it, but the path doesnt end with a slash. It needs the slash, so make a redirect to add it. This is an automatic feature of link:#api-buildgetter[.buildGetter], but not link:#api-get[.get].
- `304` (Not Modified): matching ETag - the requested resource hasn't changed since a previous download. So a response with this status only is a signal to browsers to reuse their locally cached resource instead of downloading it again. This is an automatic feature of link:#api-buildgetter[.buildGetter], but not link:#api-get[.get].
- `400` (Bad Request): the resource path is illegal, that is, resolves to an empty path or contains illegal characters: `: | < > ' " ´ * ?` or backslash or backtick.
- `404` (Not Found): a valid resource path, but it doesn't point to a readable file or a directory with an index fallback in it. Currently, it can also signify an link:#osgi-bug[empty file].
- `500` (Error): a server-side error happened. Details will be found in the server log, but not returned to the user.

{zwsp} +

[[body]]
==== body

On status-`200` responses, this is the content of the requested asset. Can be text or binary, depending on the file and type. May also carry error messages.

Empty on status-`304`.

Interally in XP (before returning it to the browser), this content is not a string but a **resource stream** from link:https://developer.enonic.com/docs/xp/stable/api/lib-io[ioLib] (see resource.getStream). This works seamlessly for returning both binary and non-binary files in the response directly to browsers. But might be less straightforward when writing tests or otherwise intercepting the output.

In link:https://developer.enonic.com/docs/enonic-cli/master/dev#start[XP dev mode], `400`- and and `404`-status errors will have the requested asset path in the body.

{zwsp} +

[[content-type]]
==== contentType

link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types[MIME type] string, after best-effort-automatically determining it from the requested asset. Will be `text/plain` on error messages.

{zwsp} +

[[headers]]
==== headers

**Default headers** optimized for immutable and link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#private_browser_caches[browser cached] resources.

Typically, there's an `ETag` and a `Cache-Control` attribute, but this may depend on whether they are active in link:../api/index#options[options], and on XP runtime mode: ETag is usually switched off in dev mode.

[NOTE]
====
**Important:** mutable assets should not be served with the default 'Cache-Control' header: `'public, max-age=31536000, immutable'`.

👉  link:#mutable-headers[Handling mutable assets]
====



{zwsp} +
{zwsp} +
{zwsp} +


[[options]]
== API: options and overrides

As described above, an options object can be added with optional attributes to **override** the link:../api/index#behaviour[default behaviour]:

.For .buildGetter:
----
{ cacheControl, contentType, etag, getCleanPath, throwErrors }
----

.For .get:
----
{ cacheControl, contentType, etag, throwErrors }
----

{zwsp} +

[[option-cachecontrol]]
==== cacheControl

(boolean/string/function) Override the default  `Cache-Control` header value (`'public, max-age=31536000, immutable'`).

    - if set as a `false` boolean, no `Cache-Control` headers are sent. A `true` boolean is just ignored.
    - if set as a string, always use that value. An empty string will act as `false` and switch off cacheControl.
    - if set as a function: `(filePathAndName, resource, mimeType) => cacheControl`. For fine-grained control which can use resource path, resolved MIMEtype string, or file content if needed. _filePathAndName_ is the asset's file path and name (relative to the JAR root, or `build/resources/main/` in dev mode). File content is by resource object: _resource_ is the output from link:https://developer.enonic.com/docs/xp/stable/api/lib-io#getresource[ioLib getResource], so your function should handle this if used. This function and the string it returns is meant to replace the default header handling.
+
NOTE: A trick: if a _cacheControl_ function returns `null`, lib-static's default Cache-Control header will be used.

An output _cacheControl_ string is used directly in the response.

👉 link:#example-cache[Usage example]

{zwsp} +

[[option-contenttype]]
==== contentType

(string/boolean/object/function) Override the built-in link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types[MIME type] detection.

    - if set as a boolean, switches MIME type handling on/off. `true` is basically ignored (keep using built-in type detection), `false` skips processing and removes the content-type header (same as an empty string)
    - if set as a non-empty string, assets will not be processed to try and find the MIME content type. Instead this value will always be preselected and returned.
    - if set as an object, keys are file types (the extensions of the asset file names _after compilation_, case-insensitive and will ignore dots), and values are Content-Type strings - for example, `{"json": "application/json", ".mp3": "audio/mpeg", "TTF": "font/ttf"}`. For files with extensions that are not among the keys in the object, the handling will fall back to the built-in handling.
    - if set as a function: `(filePathAndName, resource) => contentType`. _filePathAndName_ is the asset file path and name (relative to the JAR root, or `build/resources/main/` in dev mode). File content is by resource object: _resource_ is the output from link:https://developer.enonic.com/docs/xp/stable/api/lib-io#getresource[ioLib getResource], so your function should handle this if used.
+
NOTE: Same trick as for the _cacheControl_ function above: if a _contentType_ function returns `null`, the processing falls back to the default: built-in MIME type detection.

An output _contentType_ string is used directly in the response.

👉 link:#example-content[Usage example]

{zwsp} +

[[option-etag]]
==== etag

(boolean) The default behaviour of lib-static is to generate/handle ETag in prod, while skipping it entirely in dev mode.
    - Setting the etag parameter to `false` will turn **off** etag processing (runtime content processing, headers and handling) in **prod** too.
    - Setting it to `true` will turn it **on in dev mode** too.

👉 link:#example-etag[Usage example]

{zwsp} +

[[option-getcleanpath]]
==== getCleanPath

(function) Only used in link:#api-buildgetter[.buildGetter]. The default behaviour of the returned `getStatic` function is to take a request object, and compare the beginning of the current requested path (`request.rawPath`) to the endpoint's own root path (`request.contextPath`) and get a relative asset path below `root` (so that later, prefixing the `root` value to that relative path will give the absolute full path to the resource in the JAR). In cases where this default behaviour is not enough, you can override it by adding a `getCleanPath` param: `(request) => '<resource/path/below/root>'`. Emphasis: the returned 'clean' path from this function should be _relative to the `root` folder_, not an absolute path in the JAR.

    - **For example:** if a controller _getAnyStatic.es6_ is accessed with a link:https://developer.enonic.com/docs/xp/stable/cms/mappings[controller mapping] at _https://someDomain.com/resources/public_, then that's an endpoint with the path `resources/public` - but that can't be determined from the request. So the automatic extraction of a relative path needs a `getCleanPath` override. Super simplified here:
+
----
    const getStatic = libStatic.buildGetter(
        'my-resources',
        {
            getCleanPath: (request) => {
                if (!request.rawPath.startsWith('resources/public')) { throw Error('Ooops'); }
                return request.rawPath.substring('resources/public'.length);
            }
        }
    );
----
+
Now, since `request.rawPath` doesn't include the protocol or domain, the URL https://someDomain.com/resources/public/subfolder/target-resource.xml will give `request.rawPath` this value: `"resources/public/subfolder/target-resource.xml"`. So the `getCleanPath` function will return `"/subfolder/target-resource.xml"`, which together with the root, `"my-resources"`, will look up the resource _/my-resources/subfolder/target-resource.xml_ in the JAR (or in XP dev mode: _build/resources/main/my-resources/subfolder/target-resource.xml_).

👉 link:path#example-getcleanpath[Another usage example]

[[option-throwerrors]]
==== throwErrors

(boolean, default value is `false`) By default, the `.get` method should not throw errors when used correctly. Instead, it internally server-logs (and hash-ID-tags) errors and automatically outputs a 500 error response.

  - Setting `throwErrors` to `true` overrides this: the 500-response generation is skipped, and the error is re-thrown down to the calling context, to be handled there.
  - This does not apply to 400-bad-request and 404-not-found type "errors", they will always generate a 404-response either way. 200 and 304 are also untouched, of course.

👉 link:#example-errors[Usage example]
