= requestHandler

This function

== Parameters

[%header,cols="1%,1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type    | Attributes | Description
| request | Request | <required> | The request object
| options | object  | <optional> | Options Object

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name         ! Type    ! Attributes ! Default ! Description
! cacheControl ! CacheControlResolver ! defaultCacheControl ! <optional> ! Function that returns the cache control header value
! contentType  ! ContentTypeResolver ! <optional> ! getMimeType()  ! Function that returns the content type header value
! etag ! boolean ! <optional> ! true ! Whether to include ETag header
! index ! string ! <optional> ! 'index.html' ! Default file to serve when requesting a directory
! notFound ! NotFoundHandler ! <optional> ! notFoundResponse ! Function that returns the response object when the resource is not found
! relativePath ! RelativePathResolver ! <optional> ! getRelativeResourcePath() ! Function that returns the relative path to the resource
! root ! string ! <optional> ! '/static' ! Root path to serve files from
! staticCompress ! boolean ! <optional> ! true ! Whether to serve precompressed files (*.br, *.gz) if available and supported by the browser
! throwErrors ! boolean ! <optional> ! true ! Whether to throw errors or return a response object
!===
|===

[.lead]
Returns

*Response* : The response object.

[.lead]
Example without options

.src/main/resources/webapp/webapp.ts
[source, TypeScript]
----
import type {Request, Response} from '/lib/enonic/static';
import {requestHandler} from '/lib/enonic/static';

import Router from '/lib/router';
const router = Router();

router.get('{path:.*}', requestHandler);

export const all = (request: Request) => router.dispatch(request);
----

== Example with options
.src/main/resources/webapp/webapp.ts
[source, TypeScript]
----
import type {Request, Response} from '/lib/enonic/static';
import {
  RESPONSE_CACHE_CONTROL,
  requestHandler,
  defaultCacheControl
  } from '/lib/enonic/static';

import Router from '/lib/router';
const router = Router();

router.get('{path:.*}', (request: Request): Response => requestHandler(
  request,
  {
    cacheControl: ({contentType, path, resource}) => {
      // First do custom cache control:
      if (path.startsWith('/favicon')) {
        // Currently: public, max-age=10, s-maxage=3600, stale-while-revalidate=50
        return RESPONSE_CACHE_CONTROL.SAFE;
      }
      // Then fallback to the default cache control
      return defaultCacheControl({
        contentType,
        path,
        resource
      });
    },
    contentType: ({path, resource: _resource}) => {
      if (path.endsWith('.css')) {
        return 'text/css';
      }
      return 'application/octet-stream';
    },
    etag: true, // This is the default
    index: 'index.html', // This is the default
    relativePath: (request) => {
      // Simplification of the default implementation:
      return request.rawPath.substring(request.contextPath.length);
    },
    root: '/static',
    throwErrors: true
  }
));

export const all = (request: Request) => router.dispatch(request);
----
