= Lib-static
:toc: right

{zwsp} +
{zwsp} +


[[intro]]
== Intro

link:https://enonic.com/developer-tour[Enonic XP] library for serving assets from a folder in the application resource structure. The aim is _"perfect client-side and network caching"_ via response headers - with basic error handling included, and a simple basic usage but highly configurable (modelled akin to link:https://www.npmjs.com/package/serve-static[serve-static]).

Intended for setting up XP endpoints that serve static files in a cache-optimized way. Optimally, these should be **immutable files** (files whose content aren't meant to change, that is, can be trusted to never change without changing the file name), but lib-static also handles ETags which provide caching with dynamic files too (link:mutability#mutable-assets[more about handling mutability]).

Some relevant sources: link:https://web.dev/http-cache/[web.dev], link:https://engineering.fb.com/2017/01/26/web/this-browser-tweak-saved-60-of-requests-to-facebook/[facebook], link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching[mozilla], link:https://imagekit.io/blog/ultimate-guide-to-http-caching-for-static-assets/[imagekit], link:https://freecontent.manning.com/caching-assets/[freecontent.manning.com].

== Concepts

* <<concepts/why#, Why use lib-static instead of portal.assetUrl?>>
* <<concepts/mutability#, Assets and mutability>>

{zwsp} +

[[get-started]]
== Getting started

=== Install
Insert into `build.gradle` of your XP project, under `dependencies`, where `<version>` is the latest/requested version of this library - for example `1.0.0`:
[source,groovy,options="nowrap"]
----
dependencies {
	include 'com.enonic.lib:lib-static:<version>'
}

repositories {
    maven {
        url 'http://repo.enonic.com/public'
    }
}
----


=== Import
In any link:https://developer.enonic.com/docs/xp/stable/framework/controllers[XP controller], import the library:

[source,javascript,options="nowrap"]
----
const libStatic = require('/lib/enonic/static');
----

== Service

* <<service/standard#, Standard service>>
* <<service/custom#, Custom service>>

== API

* <<api/buildgetter#, buildGetter>>
* <<api/get#, get>>
* <<api/getStaticUrl#, getStaticUrl>>
