= Lib-static
:toc: right

{zwsp} +
{zwsp} +


[[intro]]
== Intro

link:https://enonic.com/developer-tour[Enonic XP] library for serving assets from a folder in the application resource structure. The aim is _"perfect client-side and network caching"_ via response headers - with basic error handling included.

Intended for setting up XP endpoints that serve static files in a cache-optimized way. Optimally, these should be **immutable files** (files whose content aren't meant to change, that is, can be trusted to never change without changing the file name), but lib-static also handles ETags which provide caching with dynamic files too (link:concepts/mutability#mutable-assets[more about handling mutability]).

{zwsp} +

[[get-started]]
== Getting started

=== Install
Insert into `build.gradle` of your XP project, under `dependencies`, where `<version>` is the latest/requested version of this library - for example `1.0.0`:
[source,groovy,options="nowrap"]
----
dependencies {
	include 'com.enonic.lib:lib-static:<version>'
}

repositories {
    maven {
        url 'http://repo.enonic.com/public'
    }
}
----


=== Import
In any link:https://developer.enonic.com/docs/xp/stable/framework/controllers[XP controller], import the library:

Ecma/TypeScript:
[source,typescript,options="nowrap"]
----
import {requestHandler} from '/lib/enonic/static';
----

JavaScript:
[source,javascript,options="nowrap"]
----
const libStatic = require('/lib/enonic/static');
----


== API

* <<api/requestHandler#, requestHandler>>
* <<api/types#, types>>

== Examples

== Concepts

* <<concepts/why#, Why use lib-static instead of portal.assetUrl?>>
* <<concepts/mutability#, Assets and mutability>>
