= Custom service

The standard service is a good starting point, but sometimes you need more control over how static resources are served. This is where a custom service comes in.

The static library currently provides these main functions that can be imported to create a custom service:

1. `requestHandler`
2. `etagRequestHandler`
3. `immutableRequestHandler`

requestHandler is simply a wrapper around etagRequestHandler and immutableRequestHandler. It uses the configured cacheStrategy to determine which of those to call.

== Parameters

The requestHandler function has the combined parameters of both etagRequestHandler and immutableRequestHandler. In addition one can pass a cacheStrategy parameter to "hardcode" which strategy to use, regardless of the configured cacheStrategy.

The immutableRequestHandler has all the same parameters as etagRequestHandler, since it by default fallsback to etag for html files. In addition it takes a `useEtagWhen` callback that can be used to determine if etag strategy should be used for a specific resource.

=== common

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name   | Type   | Description
| params | object | Input parameters as JSON

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name                   ! Type   ! Attributes ! Default ! Description
! request                ! object ! *required* ! ! The request object
! getContentType         ! function ! optional ! ! Used to override the default content type processing
! root                   ! string ! optional ! static ! The root folder to serve files from
! throwErrors            ! boolean ! optional ! false ! If true, throw instead of returning a 500 response
!===

|===

=== etagRequestHandler

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name   | Type   | Description
| params | object | Input parameters as JSON

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name                   ! Type   ! Attributes ! Default ! Description
! etagCacheControlHeader ! string ! optional ! max-age=3600 ! Used to override what is configured
! etagProcessing         ! string ! optional ! auto ! Used to override what is configured
!===

|===

=== immutableRequestHandler

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name   | Type   | Description
| params | object | Input parameters as JSON

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name                   ! Type   ! Attributes ! Default ! Description
! getImmutableCacheControlHeader ! string ! optional ! public, max-age=31536000, immutable ! Used to override what is configured
!  useEtagWhen         ! function ! optional ! ! Callback which is passed {contentType}. Uses etag strategy when it returns true, otherwise immutable strategy.
!===

|===

=== requestHandler

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name   | Type   | Description
| params | object | Input parameters as JSON

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name                   ! Type   ! Attributes ! Default ! Description
! cacheStrategy ! string ! optional ! undefined ! Used to override what is configured
!===

|===

== Example

./src/main/resources/services/mycustomstaticservice/mycustomstaticservice.ts
[source, TypeScript]
----
import type {
	Request,
	Response,
} from '/lib/enonic/static'; // Requires installation of @enonic-types/lib-static

import Router from '/lib/router';
import { requestHandler } from '/lib/enonic/static/service/requestHandler';


const router = Router();

router.get('{path:.*}', (request: Request): Response => {
  return requestHandler({
    // Required
    request,
    // Optional
    cacheStrategy: 'immutable',
    etagCacheControlHeader: 'no-cache
    etagProcessing: 'always',
    // getCacheControl: (path, _resource, contentType) => {
    //   if (path === 'path') {
    //     return 'path';
    //   }
    //   if (contentType === 'contentType') {
    //     return 'contentType';
    //   }
    //   return 'resource';
    // },
    getContentType:(path, resource) => {
      log.debug('getContentType path:%s', path, resource);
      return 'text/plain';
    },
    getImmutableCacheControlHeader: (path, resource, contentType) => {
      log.debug('getImmutableCacheControlHeader path:%s', path, resource, contentType);
      return 'public, max-age=2147483647, immutable';
    },
    root: 'mystaticfolder',
    throwErrors: true,
    useEtagWhen: (contentType) => {
      return contentType === 'text/html';
    }
  });
});

export const all = (request: Request) => router.dispatch(request);
----

./src/main/resources/site/pages/mypage/mypage.ts
[source, TypeScript]
----
import { getStaticUrl } from '/lib/enonic/static';

export function get(_request) {

  const url = getStaticUrl({
    path: 'styles/main.css',
    service: 'mycustomstaticservice'
  });

  return {
    body: `
<html>
  <head>
    <link rel="stylesheet" href="${url}">
  </head>
  <body>
    <h1>Hello, world!</h1>
  </body>
</html>
`,
    contentType: 'text/html'
  };
}
----
